"""Create and repair the canonical shared brain on the owner's machine."""
from __future__ import annotations

import os
from pathlib import Path

from . import agents, config, db, util

# One README per directory so a future agent never has to guess what a folder is
# for.  Written only if absent; an edited README is never clobbered.
DIR_READMES = {
    "state": "Machine-readable state. `aion.sqlite3` is the SOURCE OF TRUTH for tasks, "
             "approvals, agents, packets, errors, memory, metrics and events. "
             "`RESUME.json` is the exact resume point, `HEALTH.json` the last measured "
             "health run. Query through the `aion` CLI, never by hand-editing.",
    "private_state": "Secrets and sensitive operational data. Mode 0700. `secrets.env` is "
                     "0600 and holds `NAME=value` lines entered on this machine only. "
                     "NEVER commit, NEVER include in a backup archive, NEVER send to "
                     "WhatsApp or any chat. Excluded from `aion scan` on purpose.",
    "PROJECTS": "One subdirectory per project: briefs, specs and project-local notes. "
                "Operational status belongs in the database, not here.",
    "TASKS": "Task artifacts too large for a database row: plans, outputs, transcripts. "
             "Name files `<TASK_ID>-<slug>.<ext>` so they link back to the queue.",
    "AGENTS": "Agent-facing material. `prompts/` holds versioned role prompts, "
              "`work_orders/` the instructions handed down to cheaper models, "
              "`results/` the result packets they return.",
    "AGENTS/prompts": "Versioned agent prompts. `MASTER_CURRENT.md` is canonical; keep old "
                      "versions alongside it so a prompt change is reversible.",
    "AGENTS/work_orders": "Work orders generated by `aion context <TASK_ID>`. Each is a "
                          "self-contained brief so a cheap model needs no other context.",
    "AGENTS/results": "Result packets returned by workers: what was done, files changed, "
                      "tests run, measured results, failures, next action, resume point.",
    "APPROVALS": "One file per Tier-3 approval, for the audit trail. The live queue is in "
                 "the database; `APPROVALS.md` at the root is the generated view.",
    "MEMORY": "Durable knowledge, split by kind. Indexed for search — reach it with "
              "`aion search <query>` rather than reading files.",
    "MEMORY/facts": "Things established as true, with confidence and source date.",
    "MEMORY/decisions": "Decisions and their rationale. Do not relitigate without new evidence.",
    "MEMORY/lessons": "Reusable lessons extracted from failures. Written by `aion error-resolve`.",
    "MEMORY/preferences": "Owner preferences: tone, working hours, risk appetite, formats.",
    "RESEARCH": "Durable research findings with source and date, so nothing is rediscovered.",
    "EXPERIMENTS": "One file per experiment: hypothesis, baseline, success and failure "
                   "conditions, max cost, time window, result, decision.",
    "HANDOFFS": "Handoff packets exchanged with external AI sessions.",
    "INBOX": "Incoming AI sync packets. Files land in `pending/`, then move to "
             "`processed/` or `failed/`. Run `aion ingest-inbox`.",
    "INBOX/pending": "Drop AI SYNC PACKET files here. Processed on the next `aion boot`.",
    "INBOX/processed": "Successfully ingested packets. Already in memory — do not re-read.",
    "INBOX/failed": "Packets that could not be parsed or applied. Each has a matching error row.",
    "OUTBOX": "Packets prepared for other AI sessions or transports, ready to send.",
    "METRICS": "Model usage and performance exports. Live numbers come from `aion money`.",
    "FINANCE": "Financial evidence: invoices, statements, transaction references. "
               "Real money requires evidence; forecasts stay labelled as forecasts.",
    "LOGS": "Raw logs. Summarised by `aion today` — do not load these into a model context.",
    "BACKUPS": "Restore-tested archives from `aion backup`. Excludes private_state by design. "
               "Mode 0700, last 14 kept.",
    "CONFIG": "Local configuration that is not secret. Secrets go to private_state.",
    "SCHEMAS": "Schema definitions for packets, work orders and result packets.",
    "INDEX": "Generated retrieval indexes. Rebuildable; safe to delete.",
    "SERVICES": "Service definitions and unit files for long-running local processes.",
    "scripts": "Local operational scripts specific to this machine.",
    "FABLE": "The strong-model launch pack. Start at `FABLE_START_PROMPT.txt`.",
}

SEED_DOCS = {
    "README.md": """# AION shared brain

This directory is the **canonical operational state** of the system. The
database at `state/aion.sqlite3` is the source of truth; every markdown file
here is generated from it by `aion sync-docs` and is overwritten on the next
run, so edit state through the CLI, not by hand.

Layout:

- `state/` machine-readable state (database, RESUME.json, HEALTH.json)
- `private_state/` secrets and sensitive operational data — never committed, never sent to WhatsApp
- `INBOX/` incoming AI sync packets (`pending` -> `processed` / `failed`)
- `OUTBOX/` packets prepared for other AI sessions
- `AGENTS/` prompts, work orders and result packets
- `APPROVALS/` one file per Tier-3 approval
- `MEMORY/` durable facts, decisions, lessons, preferences
- `METRICS/`, `FINANCE/`, `LOGS/`, `BACKUPS/`, `RESEARCH/`, `EXPERIMENTS/`
- `FABLE/` the launch pack for a strong-model session
""",
    "CHANGELOG.md": "# CHANGELOG\n\nAppend-only record of material system changes.\n",
    "OWNER_SETUP_REQUIRED.md": "# OWNER SETUP REQUIRED\n\n_Regenerate with `aion owner-setup`._\n",
    "SYSTEM_STATE.md": "# SYSTEM STATE\n\n_Not generated yet. Run `aion status`._\n",
    "GLOBAL_TASKS.md": "# GLOBAL TASKS\n\n_Not generated yet._\n",
    "DECISIONS.md": "# DECISIONS\n\n_Not generated yet._\n",
    "BLOCKERS.md": "# BLOCKERS\n\n_Not generated yet._\n",
    "APPROVALS.md": "# APPROVALS\n\n_No approval pending._\n",
    "RESUME.md": "# RESUME POINT\n\n_Not generated yet._\n",
}


def ensure() -> int:
    """Idempotent: create anything missing, never overwrite existing content."""
    root = config.home()
    touched = 0
    root.mkdir(parents=True, exist_ok=True)
    for rel in config.DIRS:
        d = root / rel
        if not d.is_dir():
            d.mkdir(parents=True, exist_ok=True)
            touched += 1
    # Sensitive trees are owner-only.
    for rel in ("private_state", "BACKUPS"):
        p = root / rel
        if p.is_dir():
            os.chmod(p, 0o700)
    for rel, blurb in DIR_READMES.items():
        d = root / rel
        if not d.is_dir():
            continue
        f = d / "README.md"
        if not f.exists():
            util.atomic_write(f, f"# {rel}\n\n{blurb}\n")
            touched += 1
    for name, body in SEED_DOCS.items():
        f = root / name
        if not f.exists():
            util.atomic_write(f, body)
            touched += 1
    db.connect()
    if not db.get_meta("initialised_at"):
        db.set_meta("initialised_at", util.now())
        db.set_meta("prompt_version", config.PROMPT_VERSION)
        db.set_meta("daily_cost_cap_inr", str(config.DEFAULT_DAILY_COST_CAP_INR))
        db.set_meta("monthly_cost_cap_inr", str(config.DEFAULT_MONTHLY_COST_CAP_INR))
        db.set_meta("build_budget_cap_inr", "2000")
        db.set_meta("paused", "0")
        db.set_meta("safe_mode", "0")
    from . import notebook
    if not (root / "NOTEBOOK.md").exists():
        notebook.ensure()
        touched += 1
    agents.seed_defaults()
    _write_gitignore(root)
    return touched


def _write_gitignore(root: Path) -> None:
    f = root / ".gitignore"
    if f.exists():
        return
    util.atomic_write(f, "\n".join([
        "# The shared brain is machine state, not source. Never commit it.",
        "*", "!.gitignore", "",
    ]))


def init_secret_store() -> Path:
    """Create the 0600 secret file.  Values are entered on the PC, never chat."""
    sf = config.secrets_file()
    sf.parent.mkdir(parents=True, exist_ok=True)
    os.chmod(sf.parent, 0o700)
    if not sf.exists():
        util.atomic_write(sf, "# AION secret store. One KEY=value per line.\n"
                              "# Never commit, never paste into WhatsApp or any chat.\n", mode=0o600)
    os.chmod(sf, 0o600)
    return sf


def set_secret(name: str, value: str) -> str:
    """Store a secret locally.  The value never enters the database or logs."""
    sf = init_secret_store()
    lines = [l for l in sf.read_text(encoding="utf-8").splitlines()
             if not l.strip().startswith(f"{name}=")]
    lines.append(f"{name}={value}")
    util.atomic_write(sf, "\n".join(lines) + "\n", mode=0o600)
    db.log_event("owner", "secret.set", name, "value not recorded")
    return name


def has_secret(name: str) -> bool:
    sf = config.secrets_file()
    if not sf.exists():
        return False
    return any(l.strip().startswith(f"{name}=") and len(l.split("=", 1)[1].strip()) > 0
               for l in sf.read_text(encoding="utf-8").splitlines())
