"use strict";
const token=location.pathname.split('/').filter(Boolean)[1]; let task=null,index=0,busy=false,lastReport=null;
const $=id=>document.getElementById(id); const show=id=>{['loading','check','review','done'].forEach(x=>$(x).hidden=x!==id)};
async function call(path,options={}){const r=await fetch(`/api/taskcheck/${token}${path}`,{cache:'no-store',...options});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`Request failed (${r.status})`);return p}
function error(e){$('error').textContent=e.message||String(e)}
function answered(){return task.checks.filter(x=>x.response).length}
function deadlineText(){if(!task?.expires_at)return "";const d=new Date(task.expires_at);return `Complete by ${d.toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}`;}
function render(){const c=task.checks[index];show('check');$('deadline').textContent=deadlineText();$('counter').textContent=`CHECK ${index+1} OF ${task.checks.length}`;$('title').textContent=c.title;$('instruction').textContent=c.instruction;$('help').textContent=c.help||'No extra help.';$('expected').textContent=c.expected_result||'';$('note').value=c.note||'';$('back').disabled=index===0;$('photoLabel').hidden=!c.evidence_allowed;$('evidenceState').textContent=c.evidence?.length?`${c.evidence.length} evidence file(s) attached`:'';document.querySelectorAll('[data-answer]').forEach(b=>b.classList.toggle('selected',b.dataset.answer===c.response));$('bar').style.width=`${answered()/task.checks.length*100}%`;$('progressText').textContent=`${answered()} / ${task.checks.length}`}
async function save(answer){if(busy)return;busy=true;try{const c=task.checks[index];await call(`/check/${c.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({response:answer,note:$('note').value.trim()})});c.response=answer;c.note=$('note').value.trim();if(index<task.checks.length-1){index++;render()}else review()}catch(e){error(e)}finally{busy=false}}
function review(){show('review');$('deadline').textContent=deadlineText();const counts={PASS:0,FAIL:0,SKIP:0,UNANSWERED:0};task.checks.forEach(c=>counts[c.response||'UNANSWERED']++);$('summary').innerHTML=`<div class="summary-row"><span>PASS</span><strong>${counts.PASS}</strong></div><div class="summary-row"><span>FAIL</span><strong>${counts.FAIL}</strong></div><div class="summary-row"><span>SKIP</span><strong>${counts.SKIP}</strong></div><div class="summary-row"><span>Unanswered</span><strong>${counts.UNANSWERED}</strong></div>`;$('bar').style.width=`${answered()/task.checks.length*100}%`; $('progressText').textContent='Final review'}
document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.answer)));$('back').addEventListener('click',()=>{if(index>0){index--;render()}});$('edit').addEventListener('click',()=>{index=0;render()});$('photo').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const c=task.checks[index];$('evidenceState').textContent='Uploading…';const p=await call(`/evidence/${c.id}`,{method:'POST',headers:{'Content-Type':f.type},body:f});c.evidence=c.evidence||[];c.evidence.push(p.evidence);$('evidenceState').textContent=`${c.evidence.length} evidence file(s) attached`}catch(err){error(err)}finally{e.target.value=''}});$('submit').addEventListener('click',async()=>{try{const p=await call('/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});lastReport=p.report;show('done');$('doneStatus').textContent=`Status: ${p.report.result_status}`;$('bar').style.width='100%';$('progressText').textContent='Complete'}catch(e){error(e)}});
$('download').addEventListener('click',()=>{location.href=`/report/${token}/LUCY-TaskCheck-report.txt`});
$('share').addEventListener('click',async()=>{try{const r=await fetch(`/report/${token}/LUCY-TaskCheck-report.txt`,{cache:'no-store'});if(!r.ok)throw new Error('Report unavailable');const blob=await r.blob();const file=new File([blob],'LUCY-TaskCheck-report.txt',{type:'text/plain'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:'LUCY TaskCheck report',text:lastReport?`Task ${lastReport.taskcheck_id} · ${lastReport.result_status}`:'LUCY TaskCheck report',files:[file]})}else if(navigator.share){await navigator.share({title:'LUCY TaskCheck report',text:await blob.text()})}else{location.href=`/report/${token}/LUCY-TaskCheck-report.txt`}}catch(e){if(e.name!=='AbortError')error(e)}});
(async()=>{try{const p=await call('');task=p.task;index=Math.max(0,task.checks.findIndex(x=>!x.response));if(index<0)index=task.checks.length-1;if(task.status==='COMPLETED'||task.status==='REVIEWED'){const rp=await call('/report');lastReport=rp.report;show('done');$('doneStatus').textContent=`Status: ${lastReport.result_status}`;$('bar').style.width='100%';$('progressText').textContent='Complete'}else{render()}}catch(e){show('loading');$('loading').innerHTML='<h1>Checklist unavailable</h1><p>This link may be invalid, expired or revoked.</p>';error(e)}})();
