#!/usr/bin/env python3
"""Generate an index of planning documents with their status.

Six generations of plan files accumulated under `.lucy/planning`, `.lucy/execution`
and `docs/internal`; agents kept reading stale ones. This deterministic index
names exactly which plan is CURRENT. A document is CURRENT only if it lives in a
directory listed in CURRENT_DIRS or its first non-empty line carries
`STATUS: CURRENT`; a line `STATUS: HISTORICAL` marks it historical; anything
else is UNMARKED (treat as historical). Read-only; prints markdown to stdout.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCAN_DIRS = (".lucy/planning", ".lucy/execution", "docs/internal")
CURRENT_DIRS = (".lucy/planning/lucyos-total-recovery",)
STATUS_RE = re.compile(r"STATUS:\s*(CURRENT|HISTORICAL)", re.IGNORECASE)


def status_of(path: Path, root: Path = REPO) -> str:
    rel = path.relative_to(root).as_posix()
    if any(rel.startswith(d + "/") for d in CURRENT_DIRS):
        return "CURRENT"
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            for line in fh:
                if line.strip():
                    m = STATUS_RE.search(line)
                    return m.group(1).upper() if m else "UNMARKED"
    except OSError:
        return "UNMARKED"
    return "UNMARKED"


def collect(root: Path = REPO) -> list[tuple[str, str]]:
    rows = []
    for d in SCAN_DIRS:
        base = root / d
        if not base.is_dir():
            continue
        for p in sorted(base.rglob("*.md")):
            if p.relative_to(root).as_posix() == ".lucy/planning/INDEX.md":
                continue  # the generated index never indexes itself
            rows.append((p.relative_to(root).as_posix(), status_of(p, root)))
    return rows


def render(rows: list[tuple[str, str]]) -> str:
    counts = {}
    for _, s in rows:
        counts[s] = counts.get(s, 0) + 1
    out = ["# Planning index (generated by scripts/planning_index.py; do not edit)", "",
           "Read CURRENT documents only. HISTORICAL and UNMARKED files are evidence, not instructions.", "",
           "| Status | Document |", "|---|---|"]
    order = {"CURRENT": 0, "HISTORICAL": 1, "UNMARKED": 2}
    for path, s in sorted(rows, key=lambda r: (order[r[1]], r[0])):
        out.append(f"| {s} | `{path}` |")
    out.append("")
    out.append("Counts: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--root", default=str(REPO))
    args = p.parse_args(argv)
    print(render(collect(Path(args.root))), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
