#!/usr/bin/env python3
"""Render the human-readable protected-paths table from the machine baseline.

Prints markdown to stdout only.  This never writes into `.lucy/authority/**`
-- that directory is constitutional (see PROTECTED_PATHS.md). Fable reviews
the rendered output and applies it to the real doc by hand; this script does
not, and must not, do that itself.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BASELINE_PATH = REPO / ".lucy" / "authority" / "HIGH_MODEL_BASELINE.json"


def load_baseline(path: Path = BASELINE_PATH) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def render(baseline: dict) -> str:
    constitutional = sorted(baseline.get("constitutional_paths_no_override_possible", []))
    protected_all = sorted(baseline.get("protected_paths", []))
    constitutional_set = set(constitutional)
    protected_only = [p for p in protected_all if p not in constitutional_set]

    lines = [
        "# Protected paths (rendered from HIGH_MODEL_BASELINE.json)",
        "",
        "Generated by `scripts/render_protected_paths.py` -- do not hand-edit this",
        "section; edit the baseline and re-render instead.",
        "",
        "## Constitutional (no task override can ever cover these)",
        "",
        "| Path |",
        "|---|",
    ]
    for p in constitutional:
        lines.append(f"| `{p}` |")

    lines += [
        "",
        "## Protected (task override possible, recorded in the baseline by Fable in advance)",
        "",
        "| Path |",
        "|---|",
    ]
    for p in protected_only:
        lines.append(f"| `{p}` |")

    lines.append("")
    return "\n".join(lines)


def missing_from_doc(paths: list[str], doc_text: str) -> list[str]:
    """Return every path that does not appear verbatim anywhere in doc_text."""
    return [p for p in paths if p not in doc_text]


def main(argv=None) -> int:
    baseline = load_baseline()
    sys.stdout.write(render(baseline))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
